service: app
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  app:
    handler: main.handler
    url: true

plugins:

  - serverless-python-requirements
  - serverless-dotenv-plugin